export const BlackListGames = [
  "Games + Demos",
  "Just Chatting",
  "Special Events",
  "Sports",
  "Slots",
  "Music",
  "I'm Only Sleeping",
  "ASMR",
  "Virtual Casino",
  "Casino Jackpot",
  "Art",
  "Fitness & Health",
  "Retro",
  "Travel & Outdoors",
  "Talk Shows & Podcasts",
  "Pools, Hot Tubs, and Beaches",
  "Animals, Aquariums, and Zoos",
  "Crypto",
  "Poker",
  "Food & Drink",
  "Always On",
];
